### ISSUE TITLE
missing/hidden dependency

### ISSUE THREAD

**Issue by fcebron** [simchanu29/ros_simple_teleop#10]
Your package declares a dependency of "joy" (ros-kinetic-joy) inside "package.xml" - which is not declared inside "CMakeLists.txt", but It crashes roswtf ! Is it necessary to rely on this package ? If it is, it would be nice to tell it inside the README.md !

**Comment by fcebron** [comment]
In fact it crashes because it was missing on my system, but, I think that I would be better if it was declared.

**Comment by simchanu29** [comment]
#0cf9869515d3e1477aad01ac5a00e3b1061a11ea

**Comment by simchanu29** [comment]
#

**Comment by simchanu29** [comment]
These commit should solve the issue

**Comment by simchanu29** [comment]
Catkin or neither `simple_teleop` needs the package `Joy` to run properly, but `test.launch` needs it at runtime since it tests (among other functions) the interface to `Joy`. Therefore I think the dependency should be listed in `package.xml` and not in `CMakeLists.txt`.
