### ISSUE TITLE
Changement de nom

### ISSUE THREAD

**Issue by fcebron** [simchanu29/ros_simple_teleop#9]
Suite à tes derniers changements, le nom du package a changé, mais pas celui du dépôt... si bien que je me suis fait avoir et j'ai eu des erreurs de compilations car j'importais l'ancien nom du package. Peux-tu corriger cela en renommant ton dépot "ros_teleop" en"simple-teleop" ? stp (ça prête à confusion)

**Comment by fcebron** [comment]
Si tu fais, ça il faudra probablement changer la ligne du readme qui indique la procédure de récupération du paquet car ça va changer l'adresse github pour le git clone.

**Comment by simchanu29** [comment]
Je vais faire ça effectivement. J'hésitais à le faire du fait que j'avais pas mal de dépendances à modifier si je le faisait

**Comment by simchanu29** [comment]
Commit 1aca1a7ec8e3b73b1c0dff42185f5a43f57db886
J'ai changé le nom du repo en ros_simple_teleop avec un warning dans le README. Le package change de nom pour simple_teleop afin de se conformer aux règles de nommage de ROS.

Le commit en question est le dernier des 4 que j'ai fait
